version: '3.7'

services:
    condo-app-backend:
        image: condo-app-backend
        restart: always
        environment:
          MONGODB_URI: mongodb+srv://admin:SZY1giyttkwdIZdN@cluster0-w6bz9.mongodb.net/condo-test
          JWT_SECRET: u5hW7EkCFr4HP32Y@y
        ports:
            - "3010:3000"

    condo-app-frontend:
        image: condo-app-frontend
        restart: always
        environment:
            GRAPHQL_URL: http://localhost:3010/graphql
        ports:
            - "8080:80"
